name: Node Continuous Integration

on:
  pull_request:
    branches:
      - entrepresenteur

jobs:
  test_pull_request:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - run: yarn install --frozen-lockfile
      - run: yarn test
      - run: yarn build
